version: '1.0'
services:
  imdb-api:
    container_name: imdb-api
    build:
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .appdata/app:/app/data
    depends_on:
      - imdb-db
    environment:
      - DB_HOST=imdb-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=imdb_db
      - LOG_DIR=/app/data/logs

  imdb-db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - .appdata/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=imdb_db

  imdb-integration-tests:
    container_name: imdb-integration-tests
    build:
      dockerfile: tests/Dockerfile
    volumes:
      - .appdata/integrationtests:/app/data
    depends_on:
      - imdb-api
    environment:
      - API_HOST=imdb-api
      - API_PORT=9000